### ISSUE TITLE
fstab

### ISSUE THREAD

**Issue by cstdenis** [DtxdF/AppJail#12]
Why does my fstab look like this? Way too much escapes

cat "/usr/local/appjail/jails/manager/conf/fstab"

`\144\145\166\146\163    \57\165\163\162\57\154\157\143\141\154\57\141\160\160\152\141\151\154\57\152\141\151\154\163\57\155\141\156\141\147\145\162\57\152\141\151\154\57\57\144\145\166    devfs    rw,ruleset=5    0       0
\164\155\160\146\163    \57\165\163\162\57\154\157\143\141\154\57\141\160\160\152\141\151\154\57\152\141\151\154\163\57\155\141\156\141\147\145\162\57\152\141\151\154\57\57\144\145\166\57\163\150\155      tmpfs   rw,size=1g,mode=1777    0       0
\146\144\145\163\143\146\163    \57\165\163\162\57\154\157\143\141\154\57\141\160\160\152\141\151\154\57\152\141\151\154\163\57\155\141\156\141\147\145\162\57\152\141\151\154\57\57\144\145\166\57\146\144  fdescfs rw,linrdlnk     0       0
\154\151\156\160\162\157\143\146\163    \57\165\163\162\57\154\157\143\141\154\57\141\160\160\152\141\151\154\57\152\141\151\154\163\57\155\141\156\141\147\145\162\57\152\141\151\154\57\57\160\162\157\143 linprocfs       rw      0       0
\154\151\156\163\171\163\146\163        \57\165\163\162\57\154\157\143\141\154\57\141\160\160\152\141\151\154\57\152\141\151\154\163\57\155\141\156\141\147\145\162\57\152\141\151\154\57\57\163\171\163     linsysfs        rw      0       0
`

**Comment by DtxdF** [comment]
Hi @cstdenis

These escape characters are further processed by `mount(8)`, the intention being to allow the use of other "special" characters, such as (but not limited to) spaces.

**Comment by cstdenis** [comment]
May be better to escape only special characters instead of everything to make it more directly readable.

**Comment by DtxdF** [comment]
That file is not intended to be edited by the end user, you must use `appjail-fstab(1)`. If you want to use a created `fstab(5)` file, you can set `mount.fstab` to a specific file in your template.

See also `appjail-start(1)`.
