### ISSUE TITLE
New Jails fail to start if zpool is exec off

### ISSUE THREAD

**Issue by jskyboo** [DtxdF/AppJail#15]
New jails inherit the exec property from the zfs pool root dataset. If exec is off then thin jails will fail to start when dhcp is configured and thick jails will fail to start at all.

To replicate:
- set zfs root dataset exec to off.
```
zfs set exec=off {pool_name}
```
- create new jail
```
appjail quick jdhcp \
    vnet=em0 \
    dhcp=em0 \
    mount_devfs \
    devfs_ruleset=10 \
    start
```

Suggested Fix: On jail dataset creation explicitly set exec to on for {pool_name}/appjail/jails/{jail_name}/jail

**Comment by DtxdF** [comment]
See [appjail.conf(5)](https://man.freebsd.org/cgi/man.cgi?query=appjail.conf&apropos=0&sektion=0&manpath=FreeBSD+14.1-RELEASE+and+Ports&arch=default&format=html)

> ZOPTS  Optional ZFS parameters for datasets. You must escape characters that can be later interpreted by the shell. Default: -o compress=lz4

**Comment by jskyboo** [comment]
Good to know, thanks. I've already got it fixed for my setup but I thought it might cause issues for other new setups and exec defaulting to on would be an easy fix. Might also consider setuid.

**Comment by DtxdF** [comment]
The default value is `on` (see `zfsprops(7)`). If someone has a different one, `ZOPTS` should fix the problem, but this is not an AppJail problem, but an environment problem.
