### ISSUE TITLE
[QUESTION] OCI, CRI support?

### ISSUE THREAD

**Issue by OneOfTheJohns** [DtxdF/AppJail#3]
Hi,

I found out about this project from here https://wiki.freebsd.org/Containers , while was searching for a possible "low level container runtime" for FreeBSD, that would be at the same time OCI compatible, so it would work with different "high level container runtimes" like "containerd" or "CRI-o".
As far as i have understood from this project, it is an "low level container runtime"?

Is there any plans on making this utility to support "OCI"/high level "container runtimes"?

Thanks

**Comment by DtxdF** [comment]
Hi @OneOfTheJohns,

It is not planned, but from a container runtime point of view, AppJail is a high-level tool that works thanks to low-level tools such as rctl, cpuset, pf, tar, etc. However, it is not planned to be OCI-compliant.
