### ISSUE TITLE
Documentation online only

### ISSUE THREAD

**Issue by okalm** [DtxdF/AppJail#7]
Hello,

I don't know if you aware of  this or if it's done on purpose but I just wanted to let you know that the documentation isn't downloadable, no pdf or html.
https://readthedocs.org/projects/appjail/downloads/

Though I also noticed you've started to write man pages which is great thank you!
Keep up the good work.

**Comment by DtxdF** [comment]
Hi,

Thank you for reporting this, I will make it available soon.

> Though I also noticed you've started to write man pages which is great thank you!
> Keep up the good work.

Thanks!
